# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.6
  - nightly
os:
  - linux
  - windows
arch:
  - x64
  - x86
cache:
  directories:
    - ~/.julia/artifacts
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
